version: 2.0

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201709-01
    steps:
      - checkout
      - run: echo running test
  deploy:
    machine:
      enabled: true
      image: circleci/classic:201709-01
    steps:
      - run:
        command: |
          echo deploying via terraform
          docker-compose -f terraform.yml run trf terraform -v
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /rc-.*/
                - master
                - production
                - staging
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - production
                - staging
