version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
        command: ls
  build2:
    docker:
      - image: ubuntu:14.04
        command: ls
        working_directory: $CIRCLE_WORKING_DIRECTORY
