version: 2
jobs:
  build:
    machine: true
      image: circleci/classic:201709-01
      steps:
        - checkout
        - run:
          command: |
            echo Running test
  deploy:
    machine: true
      image: circleci/classic:201709-01
      steps:
        - run:
          command: |
            echo Running test
            docker-compose -f terraform.yml run trf terraform -v
workflows:
  version: 2
  build_test:
    jobs:
      -build
    filters:
      branches:
        only:
          - master
          - production
          - staging
          - /rc-.*/
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master # TODO remove
                - production
                - staging
