version: 2.0

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201709-01
    environment:
      - TF_VERSION: 0.10.8
      - BUILT_IMAGE: collage_web
      - IMAGE_VERSION: "${CIRCLE_BUILD_NUM}"
      - TF_VAR_image_version: "${IMAGE_VERSION}"
    steps:
      - run: env
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
