version: 2.0
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201709-01
      steps:
        - checkout
        - run: echo Running test
  deploy:
    machine:
      enabled: true
      image: circleci/classic:201709-01
      steps:
        - run: echo deploying via terraform && docker-compose -f terraform.yml run trf terraform -v
workflows:
  version: 2
  build_test:
    jobs:
      - build
    # filters:
    #   branches:
    #     only:
    #       - /rc-.*/
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - master
          #       - production
          #       - staging
          #       - qa
